// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnWZZ5pzCihjVtcCXT9LcZwduiIhEouW8',
    appId: '1:1078755763353:web:c784b53a4e2894648e8408',
    messagingSenderId: '1078755763353',
    projectId: 'budget-buddy-e6d8d',
    authDomain: 'budget-buddy-e6d8d.firebaseapp.com',
    storageBucket: 'budget-buddy-e6d8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8PxcwLVqiNMuCR5XutaT8PYNcY5jpTgo',
    appId: '1:1078755763353:android:d036020a59e6e5ad8e8408',
    messagingSenderId: '1078755763353',
    projectId: 'budget-buddy-e6d8d',
    storageBucket: 'budget-buddy-e6d8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe5ZuNysFuG2xwXG0xLTJWg7TjpPyldjc',
    appId: '1:1078755763353:ios:57b1c79ceb5cc8df8e8408',
    messagingSenderId: '1078755763353',
    projectId: 'budget-buddy-e6d8d',
    storageBucket: 'budget-buddy-e6d8d.appspot.com',
    iosBundleId: 'com.example.budgetBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe5ZuNysFuG2xwXG0xLTJWg7TjpPyldjc',
    appId: '1:1078755763353:ios:57b1c79ceb5cc8df8e8408',
    messagingSenderId: '1078755763353',
    projectId: 'budget-buddy-e6d8d',
    storageBucket: 'budget-buddy-e6d8d.appspot.com',
    iosBundleId: 'com.example.budgetBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnWZZ5pzCihjVtcCXT9LcZwduiIhEouW8',
    appId: '1:1078755763353:web:d24d432ee9e0aef98e8408',
    messagingSenderId: '1078755763353',
    projectId: 'budget-buddy-e6d8d',
    authDomain: 'budget-buddy-e6d8d.firebaseapp.com',
    storageBucket: 'budget-buddy-e6d8d.appspot.com',
  );

}